# Site Settings
title: Megan Longcor - Data Scientist & Systems Biologist
description: Pioneering the Field of Molecular Machine Learning
permalink: ':title'
baseurl: ""
url: http://megdna.github.io

analytics: GTM-ML6GH4
disqus: 
site-twitter: megdna

# Author Settings
author: Megan Longcor
author-img: https://avatars.githubusercontent.com/u/8283950
about-author: I am a Data Scientist and Systems Biologist pioneering "Molecular Machine Learning"
email: 

facebook: megdna
github: megdna
google: +Megan8
instagram: megdna
keybase: megdna
linkedin: megdna
twitter: megdna
youtube: megdna

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
