# Site Settings
title: Megan Longcor - Data Scientist & Systems Biologist
description: Pioneering the Field of Molecular Machine Learning
permalink: ':title'
baseurl: ""
url: http://megdna.github.io

analytics: meg.goatcounter.com
disqus: 

# Author Settings
author: Megan Longcor
author-img: https://avatars.githubusercontent.com/u/8283950
about-author: I am a Data Scientist and Systems Biologist pioneering "Molecular Machine Learning"
email: meg@d8a.org

facebook: 
github: megdna
instagram: 
linkedin: in/megdna
mastodon: fediscience.org/@meg
twitter: 
youtube: megdna

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
